Traceback (most recent call last):
  File "C:\Users\walki\AppData\Roaming\Python\Python39\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from sympy import *
from sympy import Matrix # get symbolic matrix methods
init_printing(use_unicode=True) # make math display good

A = np.array([[-2, 1, 0], [1, -2, 1], [0, 1, -2]]) ## numpy matrix
A_sympy = Matrix(M) ## Take numpy matrix and make it a sympy one

eigenvals, eigenvects = np.linalg.eig(A) # numpy numerical methods
print("numpy eigenvals:",eigenvals)
print("numpy eigenvects:",eigenvects)
print("sympy eigenvals:")
A_sympy.eigenvals() # sympy symbolic methods WARNING: slow for big matrices
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 8>[1;34m()[0m
[0;32m      5[0m init_printing(use_unicode[38;5;241m=[39m[38;5;28;01mTrue[39;00m) [38;5;66;03m# make math display good[39;00m
[0;32m      7[0m A [38;5;241m=[39m np[38;5;241m.[39marray([[[38;5;241m-[39m[38;5;241m2[39m, [38;5;241m1[39m, [38;5;241m0[39m], [[38;5;241m1[39m, [38;5;241m-[39m[38;5;241m2[39m, [38;5;241m1[39m], [[38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m-[39m[38;5;241m2[39m]]) [38;5;66;03m## numpy matrix[39;00m
[1;32m----> 8[0m A_sympy [38;5;241m=[39m Matrix([43mM[49m) [38;5;66;03m## Take numpy matrix and make it a sympy one[39;00m
[0;32m     10[0m eigenvals, eigenvects [38;5;241m=[39m np[38;5;241m.[39mlinalg[38;5;241m.[39meig(A) [38;5;66;03m# numpy numerical methods[39;00m
[0;32m     11[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mnumpy eigenvals:[39m[38;5;124m"[39m,eigenvals)

[1;31mNameError[0m: name 'M' is not defined
NameError: name 'M' is not defined

