Traceback (most recent call last):
  File "C:\Users\walki\AppData\Roaming\Python\Python39\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-5,5,5)
y = np.linspace(-5,5,5)
X,Y = np.meshgrid(x,y)
u = X**2
v = Y**2

q = 1e-4
r_source = np.array([0,0])
k = 9e9

def VP_eqn(x, v, mu = 1.):
    xdot, vdot = [v,-mu * (x**2 - 1)*v - x]
    return xdot, vdot

def point_charge_E(X, Y, q,r_source):
    xdot, vdot = np.zeros(X.shape), np.zeros(Y.shape)
    Xlim, Ylim = X.shape
    for i in range(Xlim):
        for j in range(Ylim):
            xloc = X[i, j]
            yloc = Y[i, j]
            xdot[i,j], vdot[i,j] = VP_eqn(xloc, yloc,mu)
    return xdot, vdot

N = 40
x = np.linspace(-3., 3., N)
v = np.linspace(-3., 3., N)
X, V = np.meshgrid(x, v)
xdot, vdot = point_charge_E(X, V,mu)
ax = plt.figure(figsize=(5,5))
Q = plt.quiver(X, V, xdot, vdot, color='k')
plt.grid()
plt.xlabel('$x$')
plt.ylabel('$v$')
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [1][0m, in [0;36m<cell line: 32>[1;34m()[0m
[0;32m     30[0m v [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m-[39m[38;5;241m3.[39m, [38;5;241m3.[39m, N)
[0;32m     31[0m X, V [38;5;241m=[39m np[38;5;241m.[39mmeshgrid(x, v)
[1;32m---> 32[0m xdot, vdot [38;5;241m=[39m point_charge_E(X, V,[43mmu[49m)
[0;32m     33[0m ax [38;5;241m=[39m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m5[39m,[38;5;241m5[39m))
[0;32m     34[0m Q [38;5;241m=[39m plt[38;5;241m.[39mquiver(X, V, xdot, vdot, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mk[39m[38;5;124m'[39m)

[1;31mNameError[0m: name 'mu' is not defined
NameError: name 'mu' is not defined

